services:
  - type: web
    name: event-booking-system
    runtime: python
    plan: free
    buildCommand: 'bash build.sh'
    startCommand: 'python manage.py migrate --no-input && python manage.py seed_demo_data && gunicorn eventbooking.wsgi:application'
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: PYTHON_VERSION
        value: '3.12.3'
      - key: WEB_CONCURRENCY
        value: '2'
